name: AIdea
description: "AIdea is app that simplifies watching videos by beautiful well written notes."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase (latest compatible)
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_analytics: ^12.1.0
  cloud_firestore: ^6.1.1

  # Local Cache
  shared_preferences: ^2.3.2

  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1

  # State Management
  provider: ^6.1.2
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^14.2.0

  # Forms & Validation (intl-safe)
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.0.0

  # Markdown & Rich Text
  flutter_markdown: ^0.7.3
  markdown_editor_plus: ^0.2.4


  # Utils
  intl: ^0.20.2
  uuid: ^4.5.0
  equatable: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
